"use client";
import Link from "next/link";
import {useEffect,useId,useRef,useState} from "react";
import {formatOwnerDate,formatOwnerTime,ownerMoney} from "@/lib/owner-dashboard";
import {filledSalesDays,salesCents,salesPeriod,salesQuery,sortSalesProducts,validSalesFilters,type SalesReport} from "@/lib/sales-report";
import {readSalesReportAction} from "./actions";
const field="min-h-12 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-3 text-base disabled:opacity-50";
const button="min-h-12 rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-medium disabled:opacity-50";
function Metric({title,value,caption}:{title:string;value:string;caption:string}) {
  return <article aria-label={title} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><h2 className="text-sm font-medium text-slate-600">{title}</h2><p className="mt-3 break-words text-xl font-bold tabular-nums text-emerald-900 sm:text-2xl">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{caption}</p></article>;
}
export default function ReportsPanel({restaurantId,initialReport,warning}:{restaurantId:string;initialReport:SalesReport;warning:string}) {
  const [report,setReport]=useState<SalesReport|null>(initialReport),[pending,setPending]=useState(false),[downloading,setDownloading]=useState(false),[error,setError]=useState(warning),[notice,setNotice]=useState("");
  const [currency,setCurrency]=useState(initialReport.totals[0]?.currency||""),[tab,setTab]=useState("daily"),[sort,setSort]=useState<"quantity"|"total">("quantity"),[legacyProducts,setLegacyProducts]=useState(false),[limit,setLimit]=useState(30);
  const busy=useRef(false),alive=useRef(true),downloadController=useRef<AbortController|null>(null),chartId=useId();
  const root=`/admin/restaurants/${restaurantId}/reports`;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;downloadController.current?.abort();};},[]);
  async function refresh(){
    if(!report||busy.current)return;busy.current=true;setPending(true);setError("");setNotice("");
    try{const result=await readSalesReportAction(restaurantId,report.filters);if(!alive.current)return;
      if(result.data){const data=result.data;setReport(data);setCurrency(old=>data.totals.some(t=>t.currency===old)?old:data.totals[0]?.currency||"");setLimit(30);}
      else{setError(result.error);if(result.denied)setReport(null);}
    }catch{if(alive.current)setError("Hesabat yüklənmədi. Yenidən cəhd et.");}
    finally{busy.current=false;if(alive.current)setPending(false);}
  }
  async function download(){
    if(!report||busy.current)return;busy.current=true;setDownloading(true);setError("");setNotice("");
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);downloadController.current=controller;
    try{
      const response=await fetch(`${root}/export?${salesQuery(report.filters)}`,{cache:"no-store",signal:controller.signal});
      if(!response.ok){const result=await response.json().catch(()=>({error:"Excel hazırlanmadı. Yenidən cəhd et."}));if(alive.current){setError(result.error||"Excel hazırlanmadı.");if(response.status===401||response.status===403)setReport(null);}return;}
      const blob=await response.blob();if(!alive.current)return;
      const href=URL.createObjectURL(blob),link=document.createElement("a");link.href=href;
      link.download=/filename="([a-zA-Z0-9_.-]+)"/.exec(response.headers.get("Content-Disposition")||"")?.[1]||"satis-hesabati.xlsx";
      document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(href),30000);
      setNotice("Excel hesabatı hazırlandı. Seçilmiş filial və tarixlər üzrə bütün sətirlər daxil edildi.");
    }catch{if(alive.current)setError("Excel yüklənmədi. Bağlantını yoxla və yenidən cəhd et.");}
    finally{clearTimeout(timer);downloadController.current=null;busy.current=false;if(alive.current)setDownloading(false);}
  }
  if(!report)return <div role="alert" className="space-y-4 rounded-2xl border border-red-200 bg-white p-6"><p className="text-sm text-red-800">{error}</p><Link href="/admin" className="inline-flex min-h-11 items-center text-sm font-semibold text-emerald-800">Hesabını yoxla</Link></div>;
  const locked=pending||downloading,total=report.totals.find(t=>t.currency===currency),branchName=report.filters.branch_id?report.branches.find(b=>b.id===report.filters.branch_id)?.name:"Bütün filiallar";
  const days=currency?filledSalesDays(report,currency):[],max=days.reduce((best,d)=>{const cents=salesCents(d.total);return cents>best?cents:best;},BigInt(0));
  const products=sortSalesProducts(report.products.filter(p=>p.currency===currency),legacyProducts,sort),branches=report.by_branch.filter(b=>b.currency===currency||b.currency===null);
  const history=`/admin/restaurants/${restaurantId}/accounts?${salesQuery(report.filters)}`;
  return <div className="space-y-5" aria-busy={locked}>
    <nav aria-label="Hesabat dövrü" className="flex flex-wrap gap-2">{([['today','Bu gün'],['week','Bu həftə'],['month','Bu ay']] as const).map(([preset,label])=>{const period=salesPeriod(report.day,preset);return <Link key={preset} href={`${root}?${salesQuery({...period,branch_id:report.filters.branch_id})}`} aria-current={period.from===report.filters.from&&period.to===report.filters.to?"page":undefined} className={`inline-flex min-h-11 items-center rounded-xl border px-4 py-3 text-sm font-semibold ${period.from===report.filters.from&&period.to===report.filters.to?"border-emerald-800 bg-emerald-800 text-white":"border-slate-200 bg-white text-slate-700"}`}>{label}</Link>;})}</nav>
    <form action={root} aria-label="Satış hesabatı filtrləri" onSubmit={event=>{const data=new FormData(event.currentTarget);if(!validSalesFilters({branch_id:data.get("branch")||null,from:data.get("from"),to:data.get("to")})){event.preventDefault();setError("Tarix aralığını düzgün seç. Ən çox 366 gün göstərilə bilər.");}}} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5">
      <div className="grid gap-4 sm:grid-cols-3"><label className="min-w-0 space-y-2 text-sm font-medium"><span>Filial</span><select name="branch" aria-label="Filial" defaultValue={report.filters.branch_id||""} disabled={locked} className={field}><option value="">Bütün filiallar</option>{report.branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.is_active?" (deaktiv)":""}</option>)}</select></label><label className="min-w-0 space-y-2 text-sm font-medium"><span>Başlanğıc tarix</span><input name="from" aria-label="Başlanğıc tarix" type="date" required defaultValue={report.filters.from} disabled={locked} className={field}/></label><label className="min-w-0 space-y-2 text-sm font-medium"><span>Son tarix</span><input name="to" aria-label="Son tarix" type="date" required defaultValue={report.filters.to} disabled={locked} className={field}/></label></div>
      <div className="flex flex-wrap gap-2"><button disabled={locked} className="min-h-12 rounded-xl bg-emerald-800 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Filtrləri tətbiq et</button><Link href={root} className="inline-flex min-h-12 items-center px-3 text-sm font-medium text-emerald-800">Filtrləri təmizlə</Link></div>
    </form>
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-sm font-semibold">{branchName}</p><p className="mt-1 text-sm leading-6 text-slate-500">{formatOwnerDate(report.filters.from)} — {formatOwnerDate(report.filters.to)} · Bakı vaxtı</p><p className="mt-1 text-xs text-slate-500">Son yenilənmə: {formatOwnerTime(report.generated_at)}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void refresh()} disabled={locked} className={button}>{pending?"Yenilənir...":"Hesabatı yenilə"}</button><button type="button" onClick={()=>void download()} disabled={locked} className="min-h-12 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{downloading?"Excel hazırlanır...":"Excel yüklə"}</button></div></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm leading-6 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    {report.totals.length>1&&<div className="space-y-2"><nav aria-label="Hesabat valyutası" className="flex flex-wrap gap-2">{report.totals.map(t=><button key={t.currency} type="button" aria-pressed={currency===t.currency} onClick={()=>{setCurrency(t.currency);setLimit(30);}} className={`min-h-11 rounded-xl border px-4 py-2 text-sm font-semibold ${currency===t.currency?"border-emerald-800 bg-emerald-50 text-emerald-900":"border-slate-200 bg-white"}`}>{t.currency}</button>)}</nav><p className="text-xs leading-5 text-slate-500">Valyutalar ayrı göstərilir. Excel-də bütün valyutalar ayrıca sətirlərdədir.</p></div>}
    {total?<><section aria-label="Satış yekunu" className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric title="Qeyd edilmiş satış" value={ownerMoney(total.total,currency)} caption="Faktiki ödənişi qeydə alınmış hesablar"/><Metric title="Bağlanan hesablar" value={total.count} caption="Ödəniş qeydi olan masalar"/><Metric title="Orta hesab" value={ownerMoney(total.average,currency)} caption="Satış məbləği / hesab sayı"/><Metric title="Satılan məhsul sayı" value={total.quantity} caption="Servis edilmiş məhsulların sayı"/></section>
      <section aria-label="Faktiki ödəniş bölgüsü" className="grid grid-cols-2 gap-3"><Metric title="Nağd" value={ownerMoney(total.cash,currency)} caption="Qarışıq ödənişin nağd hissəsi də daxil"/><Metric title="Kart" value={ownerMoney(total.card,currency)} caption="Qarışıq ödənişin kart hissəsi də daxil"/></section></>:<p className="rounded-2xl border border-slate-200 bg-white p-6 text-sm leading-6 text-slate-500">Bu seçimə uyğun satış hesabı yoxdur. Sifarişsiz bağlanan masalar satışa daxil edilmir.</p>}
    <p className="text-xs leading-5 text-slate-500">Hesabın bağlandığı tarix əsas götürülür. Ləğv edilmiş sifarişlər yekundan çıxılır. Sifarişsiz bağlanan masa: {report.empty_count}. <Link href={history} className="font-semibold text-emerald-800">Hesab tarixçəsinə bax →</Link></p>
    {report.totals.some(t=>t.legacy_count!=="0")&&<details className="rounded-2xl border border-amber-200 bg-amber-50 p-4 sm:p-5"><summary className="min-h-8 cursor-pointer text-sm font-semibold text-amber-950">Əvvəlki hesablar · ödəniş bölgüsü qeyd edilməyib</summary><div className="mt-3 space-y-3 text-sm leading-6 text-amber-950"><p>Bu hesabların faktiki kart/nağd bölgüsü saxlanmayıb. Onlar yuxarıdakı qeyd edilmiş satışa və ödəniş yekunlarına daxil deyil.</p>{report.totals.filter(t=>t.legacy_count!=="0").map(t=><p key={t.currency} className="break-words font-semibold">{t.legacy_count} hesab · {ownerMoney(t.legacy_total,t.currency)} · {t.legacy_quantity} məhsul</p>)}<Link href={history+"&method=LEGACY"} className="inline-flex min-h-11 items-center font-semibold">Əvvəlki hesabları aç →</Link></div></details>}
    <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><nav aria-label="Hesabat bölməsi" className="grid grid-cols-3 gap-2">{[['daily','Günlər'],['branches','Filiallar'],['products','Məhsullar']].map(([id,label])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>{setTab(id);setLimit(30);}} className={`min-h-12 rounded-xl px-2 py-3 text-sm font-semibold ${tab===id?"bg-emerald-800 text-white":"bg-slate-50 text-slate-700"}`}>{label}</button>)}</nav>
      {tab==="daily"&&<><h2 className="text-lg font-semibold">Gündəlik satış{currency?` · ${currency}`:""}</h2>{days.length?<>
        <div className="rounded-xl bg-emerald-50 p-3"><svg viewBox="0 0 1000 150" role="img" aria-labelledby={chartId} className="h-36 w-full"><title id={chartId}>{`Qeyd edilmiş satışın günlər üzrə dəyişməsi, ${currency}`}</title><line x1="0" y1="145" x2="1000" y2="145" stroke="#a7f3d0"/>{days.map((d,i)=>{const height=max>BigInt(0)?Number(salesCents(d.total)*BigInt(135)/max):0;const width=1000/days.length;return <rect key={d.day} x={i*width+width*0.15} y={145-height} width={width*0.7} height={height} fill="#047857" rx={Math.min(3,width/5)}><title>{`${formatOwnerDate(d.day)}: ${ownerMoney(d.total,currency)}`}</title></rect>;})}</svg><div className="flex justify-between gap-2 text-xs text-emerald-800"><span>{formatOwnerDate(report.filters.from)}</span><span className="text-right">{formatOwnerDate(report.filters.to)}</span></div></div>
        <div className="space-y-2">{days.slice().reverse().slice(0,limit).map(d=><article key={d.day} aria-label={d.day} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div className="min-w-0"><h3 className="text-sm font-semibold">{formatOwnerDate(d.day)}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{d.count} hesab · Nağd {ownerMoney(d.cash,currency)} · Kart {ownerMoney(d.card,currency)}</p>{d.legacy_count!=="0"&&<p className="mt-1 text-xs text-amber-800">Əvvəlki: {d.legacy_count} hesab · {ownerMoney(d.legacy_total,currency)}</p>}</div><p className="break-words text-sm font-bold text-emerald-900">{ownerMoney(d.total,currency)}</p></article>)}</div>{limit<days.length&&<button type="button" onClick={()=>setLimit(l=>l+30)} className={`${button} w-full`}>Daha çox gün göstər</button>}
      </>:<p className="py-4 text-sm text-slate-500">Bu aralıqda satış qeydi yoxdur.</p>}</>}
      {tab==="branches"&&<><h2 className="text-lg font-semibold">Filialların müqayisəsi{currency?` · ${currency}`:""}</h2><div className="grid gap-3 sm:grid-cols-2">{branches.map(b=><article key={`${b.id}:${b.currency}`} aria-label={b.name} className="min-w-0 space-y-3 rounded-xl border border-slate-200 p-4"><header><h3 className="break-words font-semibold">{b.name}</h3>{!b.is_active&&<p className="mt-1 text-xs text-slate-500">Deaktiv filial</p>}</header>{b.currency?<><p className="break-words text-xl font-bold text-emerald-900">{ownerMoney(b.total,b.currency)}</p><p className="text-xs leading-6 text-slate-600">{b.count} hesab · {b.quantity} məhsul<br/>Nağd: {ownerMoney(b.cash,b.currency)} · Kart: {ownerMoney(b.card,b.currency)}<br/>Orta hesab: {ownerMoney(b.average,b.currency)}</p>{b.legacy_count!=="0"&&<p className="text-xs leading-5 text-amber-800">Əvvəlki: {b.legacy_count} hesab · {ownerMoney(b.legacy_total,b.currency)}</p>}</>:<p className="text-sm text-slate-500">Bu aralıqda satış yoxdur.</p>}<Link href={`/admin/restaurants/${restaurantId}/accounts?${salesQuery({...report.filters,branch_id:b.id})}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-emerald-800">Filialın hesabları →</Link></article>)}</div>{!branches.length&&<p className="py-4 text-sm text-slate-500">Filial yoxdur.</p>}</>}
      {tab==="products"&&<><h2 className="text-lg font-semibold">Ən çox satılan məhsullar{currency?` · ${currency}`:""}</h2><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium"><span>Məhsul hesabları</span><select aria-label="Məhsul hesabları" value={legacyProducts?"legacy":"recorded"} onChange={e=>{setLegacyProducts(e.target.value==="legacy");setLimit(30);}} className={field}><option value="recorded">Ödənişi qeydə alınmış</option><option value="legacy">Əvvəlki, bölgüsü qeydsiz</option></select></label><label className="space-y-2 text-sm font-medium"><span>Sıralama</span><select aria-label="Sıralama" value={sort} onChange={e=>{setSort(e.target.value as "quantity"|"total");setLimit(30);}} className={field}><option value="quantity">Satış sayına görə</option><option value="total">Satış məbləğinə görə</option></select></label></div><p className="text-xs leading-5 text-slate-500">{products.length} məhsul · Ad məhsulun bu aralıqdakı son sifarişindən götürülür.</p>
        {products.length?<><table className="w-full table-fixed text-sm"><thead><tr className="border-b border-slate-200 text-left text-xs text-slate-500"><th scope="col" className="w-[48%] py-3 pr-2 font-medium">Məhsul</th><th scope="col" className="w-[18%] px-1 py-3 text-right font-medium">Say</th><th scope="col" className="w-[34%] py-3 pl-2 text-right font-medium">Məbləğ</th></tr></thead><tbody>{products.slice(0,limit).map(p=><tr key={`${p.id}:${p.currency}`} className="border-b border-slate-100 align-top"><td className="break-words py-4 pr-2 font-medium">{p.name}<p className="mt-1 text-xs font-normal text-slate-500">{legacyProducts?p.legacy_account_count:p.account_count} hesab</p></td><td className="break-all px-1 py-4 text-right tabular-nums">{legacyProducts?p.legacy_quantity:p.quantity}</td><td className="break-words py-4 pl-2 text-right font-semibold tabular-nums">{ownerMoney(legacyProducts?p.legacy_total:p.total,p.currency)}</td></tr>)}</tbody></table>{limit<products.length&&<button type="button" onClick={()=>setLimit(l=>l+30)} className={`${button} w-full`}>Daha çox məhsul göstər</button>}</>:<p className="py-4 text-sm text-slate-500">Bu seçimə uyğun satılan məhsul yoxdur.</p>}</>}
    </section>
  </div>;
}
