"use client";
import Image from "next/image";
import {useEffect,useState,useSyncExternalStore} from "react";
import QRCode from "qrcode";
import {publicOrigin,tableMenuPath} from "@/lib/qr-url";
type Table={id:string;name:string;table_number:number;qr_token:string};
const subscribe=()=>()=>{},browserOrigin=()=>window.location.origin,serverOrigin=()=>"";
export default function QRPrint({tables,restaurant,branch,slug,initialOrigin}:{tables:Table[];restaurant:string;branch:string;slug:string;initialOrigin:string}){
  const current=useSyncExternalStore(subscribe,browserOrigin,serverOrigin),[custom,setCustom]=useState(initialOrigin||process.env.NEXT_PUBLIC_SITE_URL||"");
  const origin=publicOrigin(custom.trim()||current),[selected,setSelected]=useState(()=>tables.map(t=>t.id));
  const [generated,setGenerated]=useState<{origin:string;images:Record<string,string>}>({origin:"",images:{}}),[error,setError]=useState("");
  useEffect(()=>{let cancelled=false;if(!origin)return;void Promise.all(tables.map(async t=>[t.id,await QRCode.toDataURL(origin+tableMenuPath(slug,t.qr_token),{width:520,margin:4,errorCorrectionLevel:"M",color:{dark:"#000000",light:"#ffffff"}})] as const))
    .then(entries=>{if(!cancelled){setGenerated({origin,images:Object.fromEntries(entries)});setError("");}}).catch(()=>{if(!cancelled)setError("QR-lər hazırlanmadı. Səhifəni yenilə.");});return()=>{cancelled=true;};},[origin,slug,tables]);
  const chosen=tables.filter(t=>selected.includes(t.id)),ready=Boolean(origin&&chosen.length&&generated.origin===origin&&chosen.every(t=>generated.images[t.id]));
  const pages:Table[][]=[];for(let i=0;i<chosen.length;i+=4)pages.push(chosen.slice(i,i+4));
  return <div className="qr-print-root space-y-5"><section className="qr-screen-only space-y-4 rounded-2xl border bg-white p-5"><h1 className="text-2xl font-bold">QR-ləri çap et</h1><p className="text-sm leading-6 text-slate-500">{restaurant} · {branch}. A4 vərəqdə 4 masa. Çap pəncərəsində printer seç və ya “Save as PDF” ilə saxla.</p><label className="block space-y-2 text-sm"><span>QR üçün yayımlanmış sayt ünvanı</span><input aria-label="Çap üçün sayt ünvanı" type="url" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="https://layihe.vercel.app" className="min-h-12 w-full rounded-xl border px-3 text-base"/></label>{!origin&&<p className="text-sm text-amber-800">Telefonla açılan https:// sayt ünvanını yaz.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex flex-wrap items-center gap-3"><button onClick={()=>setSelected(tables.map(t=>t.id))} className="min-h-11 rounded-xl border px-3 text-sm">Hamısını seç</button><button onClick={()=>setSelected([])} className="min-h-11 rounded-xl border px-3 text-sm">Seçimi təmizlə</button><span className="text-sm">{chosen.length} masa · {pages.length} vərəq</span></div><div className="grid max-h-52 grid-cols-2 gap-2 overflow-y-auto sm:grid-cols-3">{tables.map(t=><label key={t.id} className="flex min-w-0 items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span className="break-words">{t.name}</span></label>)}</div><button disabled={!ready} onClick={()=>window.print()} className="min-h-12 w-full rounded-xl bg-emerald-800 px-4 font-semibold text-white disabled:opacity-40">{ready?"Seçilən QR-ləri çap et":chosen.length&&origin?"QR-lər hazırlanır...":"Çap üçün masa və ünvan seç"}</button></section>
    <div className="space-y-5">{pages.map((page,index)=><section key={index} aria-label={`QR çap vərəqi ${index+1}`} className="qr-print-sheet grid grid-cols-1 gap-4 rounded-xl bg-white p-4 sm:grid-cols-2">{page.map(t=><article key={t.id} className="qr-print-card flex min-w-0 flex-col items-center justify-center gap-3 rounded-xl border-2 border-black p-5 text-center"><p className="qr-brand break-words text-lg font-bold">{restaurant}</p><p className="qr-branch break-words text-xs">{branch}</p>{generated.origin===origin&&generated.images[t.id]?<Image alt={`${t.name} QR kod`} src={generated.images[t.id]} width={240} height={240} unoptimized className="qr-image h-52 w-52"/>:<div className="h-52 w-52 py-20 text-sm text-slate-400">QR hazırlanır</div>}<h2 className="qr-table break-words text-2xl font-bold">{t.name}</h2><p className="text-sm">Menyunu açmaq üçün QR-i oxut</p></article>)}</section>)}</div>
    <style>{`@page{size:A4;margin:10mm;} @media print{body{background:white!important;} body:has(.qr-print-root) nav,body:has(.qr-print-root) header,.qr-screen-only{display:none!important;} main:has(.qr-print-root){padding:0!important;margin:0!important;background:white!important;min-height:0!important;} .qr-print-root{margin:0!important;} .qr-print-root>div{margin:0!important;} .qr-print-sheet{display:grid!important;grid-template-columns:1fr 1fr!important;grid-template-rows:125mm 125mm!important;gap:8mm!important;width:190mm!important;height:265mm!important;margin:0!important;padding:0!important;break-after:page;break-inside:avoid;} .qr-print-sheet:last-child{break-after:auto;} .qr-print-card{height:125mm!important;box-sizing:border-box;break-inside:avoid;border-radius:3mm!important;padding:5mm!important;gap:3mm!important;overflow:hidden;} .qr-image{width:48mm!important;height:48mm!important;} .qr-brand{max-height:18mm;overflow:hidden;font-size:16pt!important;} .qr-branch{max-height:12mm;overflow:hidden;} .qr-table{max-height:25mm;overflow:hidden;font-size:20pt!important;}}`}</style>
  </div>;
}
