"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {operationsError} from "@/lib/restaurant-operations";
type Attempt={start:number;count:number;prefix:string;request:string};
export default function BulkTables({restaurantId,branchId,suggestedNumber}:{restaurantId:string;branchId:string;suggestedNumber:number}){
  const router=useRouter(),[start,setStart]=useState(String(suggestedNumber)),[count,setCount]=useState("20"),[prefix,setPrefix]=useState("Masa"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const [attempt,setAttempt]=useState<Attempt|null>(null),pending=useRef(false);
  async function submit(){if(pending.current)return;const input=attempt||{start:Number(start),count:Number(count),prefix:prefix.trim(),request:crypto.randomUUID()};
    if(!Number.isInteger(input.start)||input.start<1||!Number.isInteger(input.count)||input.count<1||input.count>100||!input.prefix||input.prefix.length>120||input.start+input.count-1>2147483647){setError(operationsError("INVALID_TABLE_BATCH"));return;}
    pending.current=true;setBusy(true);setError("");setSuccess("");setAttempt(input);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
    try{const result=await createClient().rpc("create_tables_batch",{p_restaurant_id:restaurantId,p_branch_id:branchId,p_start:input.start,p_count:input.count,p_prefix:input.prefix,p_request_id:input.request}).abortSignal(controller.signal);
      if(result.error){if(result.error.code==="P0001"||result.error.code==="42501"||result.error.code==="23505"){setAttempt(null);setError(operationsError(result.error.code==="42501"?"FORBIDDEN":result.error.code==="23505"?"TABLE_NUMBER_EXISTS":result.error.message));}else setError("Cavab alınmadı. Eyni masa qrupunu yenidən yoxla; təkrar masalar yaranmayacaq.");return;}
      if(!result.data){setError("Cavab alınmadı. Eyni masa qrupunu yenidən yoxla.");return;}
      setAttempt(null);setSuccess(`${input.count} masa QR-lərlə birlikdə yaradıldı. QR-ləri çap et düyməsindən çap görünüşünü aç.`);setStart(String(Math.min(2147483647,input.start+input.count)));router.refresh();
    }catch{setError("Bağlantı alınmadı. Eyni masa qrupunu yenidən yoxla.");}finally{clearTimeout(timer);pending.current=false;setBusy(false);}}
  return <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Masaları toplu yarat</h2><p className="text-sm leading-6 text-slate-500">Say yaz: hər masaya ayrıca nömrə və QR veriləcək. Mövcud nömrələr dəyişdirilmir. Bir dəfəyə 1–100 masa.</p><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium"><span>Başlanğıc masa nömrəsi</span><input aria-label="Başlanğıc masa nömrəsi" type="number" min={1} max={2147483647} value={start} disabled={busy||Boolean(attempt)} onChange={e=>setStart(e.target.value)} className="min-h-12 w-full rounded-xl border px-3 text-base"/></label><label className="space-y-2 text-sm font-medium"><span>Masa sayı</span><input aria-label="Masa sayı" type="number" min={1} max={100} value={count} disabled={busy||Boolean(attempt)} onChange={e=>setCount(e.target.value)} className="min-h-12 w-full rounded-xl border px-3 text-base"/></label></div><label className="block space-y-2 text-sm font-medium"><span>Masa adının başlanğıcı</span><input aria-label="Masa adının başlanğıcı" value={prefix} maxLength={120} disabled={busy||Boolean(attempt)} onChange={e=>setPrefix(e.target.value)} className="min-h-12 w-full rounded-xl border px-3 text-base"/></label><p className="text-xs text-slate-500">Nümunə: {prefix.trim()||"Masa"} {start||"1"} … {prefix.trim()||"Masa"} {Number(start||1)+Number(count||1)-1}</p>{error&&<p role="alert" className="text-sm leading-6 text-red-700">{error}</p>}{success&&<p role="status" className="text-sm leading-6 text-emerald-800">{success}</p>}<button disabled={busy} onClick={()=>void submit()} className="min-h-12 w-full rounded-xl bg-emerald-800 px-4 font-semibold text-white disabled:opacity-40">{busy?"Yaradılır...":attempt?"Eyni masa qrupunu yenidən yoxla":"Masaları və QR-ləri yarat"}</button></section>;
}
