"use client";
import Link from "next/link";
import {useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {formatOwnerTime} from "@/lib/owner-dashboard";
import {operationsError,platformStatusLabels,type PlatformBoard,type PlatformRestaurant} from "@/lib/restaurant-operations";
const control="min-h-12 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-base disabled:opacity-40";
function RestaurantRow({r,busy,onSave}:{r:PlatformRestaurant;busy:boolean;onSave:(r:PlatformRestaurant,status:PlatformRestaurant["status"],active:boolean)=>Promise<void>}){
  const [status,setStatus]=useState(r.is_active?r.status:"inactive");
  return <article aria-label={r.name} className="min-w-0 space-y-4 rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><Link href={`/admin/restaurants/${r.id}`} className="break-words text-lg font-bold text-emerald-800">{r.name}</Link><p className="break-all text-xs text-slate-500">{r.slug}</p></div><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold">{r.is_active?platformStatusLabels[r.status]:"Deaktiv"}</span></div><p className="text-xs text-slate-500">{r.branches} filial · {r.tables} masa · {r.staff} aktiv işçi hesabı</p><div><label className="block space-y-2 text-sm"><span>Restoran statusu</span><select aria-label={`${r.name} statusu`} value={status} disabled={busy} onChange={e=>setStatus(e.target.value as keyof typeof platformStatusLabels)} className={control}>{Object.entries(platformStatusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><div className="flex flex-wrap gap-2"><button disabled={busy||status===(r.is_active?r.status:"inactive")} onClick={()=>{if((status==="suspended"||status==="inactive")&&!window.confirm(`${r.name} üçün giriş və sifariş qəbulu dayandırılacaq. Davam et?`))return;void onSave(r,status==="inactive"?r.status:status as PlatformRestaurant["status"],status!=="inactive");}} className="min-h-12 rounded-xl bg-emerald-800 px-4 text-sm font-semibold text-white disabled:opacity-40">Yadda saxla</button><Link href={`/admin/restaurants/${r.id}/owners`} className="flex min-h-12 items-center rounded-xl border px-4 text-sm">Sahib hesabı</Link><Link href={`/admin/restaurants/${r.id}`} className="flex min-h-12 items-center rounded-xl border px-4 text-sm">Restoranı aç</Link></div></article>;
}
export default function PlatformPanel({initialBoard}:{initialBoard:PlatformBoard}){
  const [board,setBoard]=useState<PlatformBoard|null>(initialBoard),[search,setSearch]=useState(initialBoard.filters.search),[status,setStatus]=useState(initialBoard.filters.status||""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");const pending=useRef(false);
  async function read(limit=30){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const result=await createClient().rpc("platform_restaurants_board",{p_search:search.trim()||null,p_status:status||null,p_limit:limit}).abortSignal(controller.signal);if(result.error?.code==="42501"){setBoard(null);throw new Error("Bu hesaba platforma admini icazəsi verilməyib.");}if(result.error||!result.data)throw new Error("Restoranlar yenilənmədi. Yenidən yoxla.");setBoard(result.data as PlatformBoard);}finally{clearTimeout(timer);}}
  async function refresh(limit=30){if(pending.current)return;pending.current=true;setBusy(true);setError("");try{await read(limit);}catch(e){setError(e instanceof Error?e.message:"Bağlantı alınmadı.");}finally{pending.current=false;setBusy(false);}}
  async function save(r:PlatformRestaurant,next:PlatformRestaurant["status"],active:boolean){if(pending.current)return;pending.current=true;setBusy(true);setError("");setNotice("");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const result=await createClient().rpc("platform_update_restaurant",{p_restaurant_id:r.id,p_status:next,p_is_active:active,p_version:r.version}).abortSignal(controller.signal);if(result.error){if(result.error.code==="42501")setBoard(null);throw new Error(operationsError(result.error.code==="42501"?"FORBIDDEN":result.error.message));}if(!result.data)throw new Error("Cavab alınmadı. Cari vəziyyət yenilənir; statusu yoxla.");setNotice(`${r.name} yeniləndi.`);}catch(e){setError(e instanceof Error?e.message:"Cavab alınmadı. Cari vəziyyəti yoxla.");}finally{clearTimeout(timer);try{await read(board?.filters.limit||30);}catch{}pending.current=false;setBusy(false);}}
  return <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><h2 className="text-xl font-bold">Platformadakı restoranlar</h2>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}{board&&<><form onSubmit={e=>{e.preventDefault();void refresh();}} className="grid items-end gap-3 sm:grid-cols-[1fr_180px_auto]"><label className="space-y-2 text-sm"><span>Restoran axtar</span><input aria-label="Restoran axtar" value={search} maxLength={80} disabled={busy} onChange={e=>setSearch(e.target.value)} placeholder="Ad və ya keçid adı" className={control}/></label><label className="space-y-2 text-sm"><span>Status filtri</span><select aria-label="Restoran status filtri" value={status} disabled={busy} onChange={e=>setStatus(e.target.value)} className={control}><option value="">Bütün statuslar</option>{Object.entries(platformStatusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button disabled={busy} className="min-h-12 rounded-xl bg-emerald-800 px-4 font-semibold text-white disabled:opacity-40">{busy?"Yenilənir...":"Axtar / yenilə"}</button></form><p className="text-xs text-slate-500">{board.restaurants.length} / {board.count} restoran · Son yenilənmə: {formatOwnerTime(board.generated_at)}</p><div className="grid items-start gap-4 lg:grid-cols-2">{board.restaurants.map(r=><RestaurantRow key={`${r.id}:${r.version}`} r={r} busy={busy} onSave={save}/>)}</div>{!board.restaurants.length&&<p className="py-5 text-center text-sm text-slate-500">Bu seçimə uyğun restoran yoxdur.</p>}{BigInt(board.count)>BigInt(board.restaurants.length)&&(board.filters.limit<150?<button disabled={busy} onClick={()=>void refresh(board.filters.limit+30)} className={control}>Daha çox restoran göstər</button>:<p className="text-sm text-slate-500">Daha dəqiq nəticə üçün restoran adı ilə axtar.</p>)}<details className="rounded-xl bg-slate-50 p-4"><summary className="min-h-8 cursor-pointer font-semibold">Son status dəyişiklikləri</summary><div className="mt-3 space-y-2">{board.events.map(e=><p key={e.id} className="break-words text-sm leading-6">{e.restaurant} · {e.is_active?platformStatusLabels[e.status as keyof typeof platformStatusLabels]:"Deaktiv"} · {formatOwnerTime(e.at)}</p>)}{!board.events.length&&<p className="text-sm text-slate-500">Hələ status dəyişiklikləri yoxdur.</p>}</div></details></>}</section>;
}
